language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch    # failing at 3.7-dev
# command to install dependencies
install:
  - sudo apt-get install libc6
  - sudo apt-get install gfortran
  - pip install -U .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
